### Sign Up
# POST https://ascii-dungeons.herokuapp.com/graphql
POST http://localhost:5000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation ($params: UserCreateInput!) {
  createUser(params: $params) {
    user {
      id
      email
      displayName
    }
    token
  }
}

{
  "user": {
    "displayName":"Test User",
    "email":"test@ascii.com",
    "password":"ascii123"
  }
}

### Login
# POST https://ascii-dungeons.herokuapp.com/graphql
POST http://localhost:5000/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation($params: UserLoginInput!) {
  loginUser(params: $params) {
    user {
      id
      email
      displayName
    }
    token
  }
}

{
  "user": {
    "email":"test@ascii.com",
    "password":"pass123"
  }
}